### PR TITLE
Add waffle.io badge

### PR DESCRIPTION
**Pull request by jaysonsantos**
This change is [Reviewable](https://reviewable.io/reviews/deinfoxication/backend/9)

### CODE REVIEW

**Comment by andreoliwa** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[README.md, line 4 [r1]](https://reviewable.io:443/reviews/deinfoxication/backend/9#-KPUIUUAccKq4FPZCXWR:-KPUIUUAccKq4FPZCXWS:bnlzdfu) ([raw file](https://github.com/deinfoxication/backend/blob/341fd74401c1f32805be943ccd69f61a0cdb365f/README.md#L4)):_

> ``` Markdown
> 
> ## Shiny badges
> [Stories in Ready](http://waffle.io/deinfoxication/backend)
> ```

Add also "in progress"?
`https://badge.waffle.io/deinfoxication/backend.svg?label=In%20Progress&title=In%20Progress`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/deinfoxication/backend/9)_

**Comment by jaysonsantos** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[README.md, line 4 [r1]](https://reviewable.io:443/reviews/deinfoxication/backend/9#-KPUIUUAccKq4FPZCXWR:-KPUWZldyQpqH6FMGWMP:b-896fix) ([raw file](https://github.com/deinfoxication/backend/blob/341fd74401c1f32805be943ccd69f61a0cdb365f/README.md#L4)):_
<details><summary>

<i>Previously, andreoliwa (Wagner Augusto Andreoli) wrote…</i></summary>



> Add also "in progress"?
> `https://badge.waffle.io/deinfoxication/backend.svg?label=In%20Progress&title=In%20Progress`
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/deinfoxication/backend/9)_

**Comment by andreoliwa** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/deinfoxication/backend/9)_

**Comment by andreoliwa** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/deinfoxication/backend/9)_

**Pull request merged**
