### PR TITLE
Start a basic structure, let's discuss about the project's structure

### PR DESCRIPTION
**Pull request by jaysonsantos**
@andreoliwa Let's leave this open untill we finish add a basic structure for the project.
What are your suggestions? deinfoxication/app1,app2,app3, deinfoxication/apps/app1,app2,app3, or something else?

---
This change is [Reviewable](https://reviewable.io/reviews/deinfoxication/backend/1)

### CODE REVIEW

**Comment by andreoliwa** [comment]
@jaysonsantos, what do you mean by "app1", "app2" and "app3"? Aren't we using only one app for the backend?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/deinfoxication/backend/1#-:-KP23LgNxunQf3lvBA1X:b-pqglml)*

**Comment by jaysonsantos** [comment]
I mean that we would have the user app, feeds app and etc... no?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/deinfoxication/backend/1#-:-KP2QJbqaBaur2yum4xO:b-f4jqc1)*

**Comment by andreoliwa** [comment]
Ah, ok, then I prefer directories without the subfolder "apps".
But we can change it later, if it becomes messy.

**Comment by andreoliwa** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.flake8, line 3 \[r2\]](https://reviewable.io:443/reviews/deinfoxication/backend/1#-KP9_3dBSf0VebmYTf6G:-KP9_3dCmb7wTMh4W5rr:b4izn50) ([raw file](https://github.com/deinfoxication/backend/blob/437006d3f3cbae3a18558e455b7c8607eda58c66/.flake8#L3)):*
> ```
> [flake8]
> # E501 = line too long
> ignore = E501
> ```

We could use `max-line-length=120` instead of ignoring line length. It's a reasonable value, no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/deinfoxication/backend/1)*

**Comment by andreoliwa** [comment]
Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.flake8, line 3 \[r2\]](https://reviewable.io:443/reviews/deinfoxication/backend/1#-KP9_3dBSf0VebmYTf6G:-KP9i3cUf3d8lwuWkfi_:b32w0x) ([raw file](https://github.com/deinfoxication/backend/blob/437006d3f3cbae3a18558e455b7c8607eda58c66/.flake8#L3)):*
<details><summary><i>Previously, andreoliwa (Wagner Augusto Andreoli) wrote…</i></summary>
> We could use `max-line-length=120` instead of ignoring line length. It's a reasonable value, no?
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/deinfoxication/backend/1)*

**Comment by jaysonsantos** [comment]
Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[.flake8, line 3 \[r2\]](https://reviewable.io:443/reviews/deinfoxication/backend/1#-KP9_3dBSf0VebmYTf6G:-KPA4BJwN-UauzoV_51o:b-896fix) ([raw file](https://github.com/deinfoxication/backend/blob/437006d3f3cbae3a18558e455b7c8607eda58c66/.flake8#L3)):*
<details><summary><i>Previously, andreoliwa (Wagner Augusto Andreoli) wrote…</i></summary>
> OK
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/deinfoxication/backend/1)*

**Comment by andreoliwa** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/deinfoxication/backend/1)*

**Comment by andreoliwa** [comment]
Reviewed 2 of 4 files at r5, 9 of 10 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/deinfoxication/backend/1)*

**Pull request merged**
